export const mockStarsData = [
  {
    id: '1',
    status: 'current',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '2',
    status: 'rewarded',
    petName: 'Jack',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '3',
    status: 'current',
    petName: 'Jack',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '4',
    status: 'starsexpired',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '5',
    status: 'starsexpired',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '6',
    status: 'starsexpired',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '7',
    status: 'current',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/10/24',
    expiryDate: '',
    size: 'Large',
  },
  {
    id: '8',
    status: 'current',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/09/24',
    expiryDate: '01/09/25',
    size: 'Large',
  },
  {
    id: '9',
    status: 'current',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/08/24',
    expiryDate: '01/08/25',
    size: 'Large',
  },
  {
    id: '10',
    status: 'expiring',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/11/24',
    expiryDate: '01/12/24',
    size: 'Large',
  },
];

export const mockRewardsData = [
  {
    id: '1',
    status: 'issued',
    petName: 'Blue',
    product: 'Bravecto',
    issueDate: '01/11/24',
    redeemedDate: '',
    expiryDate: '01/05/25',
    size: 'Large',
    wholesaler: '',
    deliveryNote: '',
    dnIssueDate: '',
  },
  {
    id: '2',
    status: 'redeemed',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/08/24',
    redeemedDate: '01/08/24',
    expiryDate: '',
    size: 'Large',
    wholesaler: '',
    deliveryNote: '',
    dnIssueDate: '',
  },
  {
    id: '3',
    status: 'reconciled',
    petName: 'Buddy',
    product: 'Bravecto',
    issueDate: '01/08/24',
    redeemedDate: '01/08/24',
    expiryDate: '',
    size: 'Large',
    wholesaler: 'ABC',
    deliveryNote: '12345678901',
    dnIssueDate: '01/12/24',
  },
  {
    id: '4',
    status: 'expired',
    petName: 'Blue',
    product: 'Bravecto',
    issueDate: '01/06/24',
    redeemedDate: '',
    expiryDate: '01/12/24',
    size: 'Large',
    wholesaler: '',
    deliveryNote: '',
    dnIssueDate: '',
  },
];
